//=====================================================================
//
// WARNING:      Do not edit this generated file
// Generated by: UnitTestGenerator.pl
// Version:      1.15
// Matrix:       association_move.txt
//
//=====================================================================

package org.xtuml.bp.ui.canvas.test.assoc;

import java.io.File;

import java.lang.Exception;
import junit.framework.Test;
import junit.framework.TestSuite;
import org.xtuml.bp.ui.canvas.test.assoc.*;

public class AssociationMoveTestSuite extends TestSuite {

    /**
     * Returns the suite.  This is required to
     * use the JUnit Launcher.
     */
    public static Test suite() {
        return new AssociationMoveTestSuite();
    }

    /**
     * Construct the test suite.
     */
    public AssociationMoveTestSuite()
    {
        addTest(new TestSuite(AssociationMove_0.class));
        addTest(new TestSuite(AssociationMove_1.class));
    }
}

