//=====================================================================
//
// NOTE: This file was generated, but is maintained by hand.
// Generated by: UnitTestGenerator.pl
// Version:      1.15
// Matrix:       oal_autocomplete_matrix.txt
//
//=====================================================================

package org.xtuml.bp.als.oal.test.completion;

import org.eclipse.ui.IEditorPart;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import org.xtuml.bp.core.*;
import org.xtuml.bp.core.common.NonRootModelElement;
import org.xtuml.bp.test.common.*;
import org.xtuml.bp.ui.canvas.*;
import org.xtuml.bp.ui.graphics.editor.*;
import org.xtuml.bp.ui.canvas.test.*;

public class OalAutoComplete extends CanvasTest {
    public static boolean generateResults = false;
    public static boolean useDrawResults = true;

    String test_id = "";

    protected String getResultName() {
        return getClass().getSimpleName() + "_" + test_id;
    }

    protected GraphicalEditor fActiveEditor;

    protected GraphicalEditor getActiveEditor() {
        return fActiveEditor;
    }

    public OalAutoComplete(String subTypeClassName, String subTypeArg0) {
        super(subTypeClassName, subTypeArg0);
    }

    protected String getTestId(String src, String dest, String count) {
        return "test_" + count;
    }

    @Before
    public void setUp() throws Exception {
        super.setUp();
    }

    @After
    public void tearDown() throws Exception {
        super.tearDown();
    }

    /**
     * "AB" is one of the degrees of freedom as specified in this issues
     * test matrix.
     * This routine gets the "AB" instance from the given name.
     * 
     * @param element The degree of freedom instance to retrieve
     * @return A model element used in the test as specified by the test matrix
     */
    NonRootModelElement selectAB(String element) {
        return selectAB(element, null);
    }

    /**
     * "AB" is one of the degrees of freedom as specified in this issues
     * test matrix.
     * This routine gets the "AB" instance from the given name.
     * 
     * @param element The degree of freedom instance to retrieve
     * @param extraData Extra data needed for selection
     * @return A model element used in the test as specified by the test matrix
     */
    NonRootModelElement selectAB(String element, Object extraData) {
        NonRootModelElement nrme = null;
        if (element.equalsIgnoreCase("A10B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A10B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A10B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A10B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A10B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A10B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A10B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A10B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A10B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A10B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A10B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A11B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A12B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A13B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A14B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A15B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A16B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A17B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A18B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A19B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A1B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A20B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A21B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A22B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A23B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A24B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A25B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A26B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A27B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A28B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A29B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A2B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A30B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A31B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A32B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A33B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A3B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A4B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A5B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A6B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A7B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A8B9")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B11")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B3")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B4")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B5")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B6")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B7")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B8")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("A9B9")) {
            //TODO: Implement
        } else        assertTrue("An instance with degree of freedom type \"AB\" was not found.  Instance Name: " + element + ".", nrme!=null);
        return nrme;
    }

    /**
     * "CD" is one of the degrees of freedom as specified in this issues
     * test matrix.
     * This routine gets the "CD" instance from the given name.
     * 
     * @param element The degree of freedom instance to retrieve
     * @return A model element used in the test as specified by the test matrix
     */
    NonRootModelElement selectCD(String element) {
        return selectCD(element, null);
    }

    /**
     * "CD" is one of the degrees of freedom as specified in this issues
     * test matrix.
     * This routine gets the "CD" instance from the given name.
     * 
     * @param element The degree of freedom instance to retrieve
     * @param extraData Extra data needed for selection
     * @return A model element used in the test as specified by the test matrix
     */
    NonRootModelElement selectCD(String element, Object extraData) {
        NonRootModelElement nrme = null;
        if (element.equalsIgnoreCase("C1D1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("C1D2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("C2D1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("C2D2")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("C3D1")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("C3D2")) {
            //TODO: Implement
        } 
        assertTrue("An instance with degree of freedom type \"CD\" was not found.  Instance Name: " + element + ".", nrme!=null);
        return nrme;
    }

    /**
     * This routine performs the action associated with a matrix cell.
     * The parameters represent model instances aquired based on the specifed
     * column instance and row instance.
     * 
     * @param columnInstance Model instance from the column
     * @param rowInstance Model instance from the row
     */
    void CD_AB_Action(NonRootModelElement columnInstance, NonRootModelElement rowInstance) {
        //TODO: Implement
    }

    /**
    * This function verifies an expected result.
    *
    * @param source A model element instance aquired through a action taken
    *               on a column of the matrix.
    * @param destination A model element instance aquired through a action taken
    *                    taken on a row of the matrix.
    * @return true if the test succeeds, false if it fails
    */
    boolean checkResult_exists(NonRootModelElement source, NonRootModelElement destination) {
        boolean exists = false;
        
        return exists;
    }


    /**
    * This function verifies an expected result.
    *
    * @param source A model element instance aquired through a action taken
    *               on a column of the matrix.
    * @param destination A model element instance aquired through a action taken
    *                    taken on a row of the matrix.
    * @return true if the test succeeds, false if it fails
    */
    boolean checkResult_non(NonRootModelElement source, NonRootModelElement destination) {
        boolean non = false;
        //TODO: Implement
        return non;
    }


}
