//=====================================================================
//
// WARNING:      Do not edit this generated file
// Generated by: UnitTestGenerator.pl
// Version:      1.15
// Matrix:       9761_9762_find_declarations_matrix.txt
//
//=====================================================================

package org.xtuml.bp.ui.text.editor.oal.opendeclaration;

import org.eclipse.ui.IEditorPart;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import org.xtuml.bp.core.*;
import org.xtuml.bp.core.common.NonRootModelElement;
import org.xtuml.bp.test.common.*;
import org.xtuml.bp.ui.canvas.*;
import org.xtuml.bp.ui.graphics.editor.*;
import org.xtuml.bp.ui.canvas.test.*;

public class OpenDeclarationTests_26 extends OpenDeclarationTests {

    protected String getResultName() {
        return super.getResultName();
    }

    public OpenDeclarationTests_26() {
        super("OpenDeclarationTests_26", null);
    }

    @Before
    public void setUp() throws Exception {
        super.setUp();
    }

    @After
    public void tearDown() throws Exception {
        super.tearDown();
    }


    /**
     * Perform the test for the given matrix column (T10L10) and row (E01P02M02C01).
     * 
     */
    @Test
    public void testT10L10_E01P02M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E01P02M02C01", "1");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E01P02M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E02P02M02C01).
     * 
     */
    @Test
    public void testT10L10_E02P02M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E02P02M02C01", "2");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E02P02M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E03P02M02C01).
     * 
     */
    @Test
    public void testT10L10_E03P02M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E03P02M02C01", "3");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E03P02M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E04P02M02C01).
     * 
     */
    @Test
    public void testT10L10_E04P02M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E04P02M02C01", "4");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E04P02M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E05P02M02C01).
     * 
     */
    @Test
    public void testT10L10_E05P02M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E05P02M02C01", "5");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E05P02M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E01P03M02C01).
     * 
     */
    @Test
    public void testT10L10_E01P03M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E01P03M02C01", "6");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E01P03M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E02P03M02C01).
     * 
     */
    @Test
    public void testT10L10_E02P03M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E02P03M02C01", "7");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E02P03M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E03P03M02C01).
     * 
     */
    @Test
    public void testT10L10_E03P03M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E03P03M02C01", "8");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E03P03M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E04P03M02C01).
     * 
     */
    @Test
    public void testT10L10_E04P03M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E04P03M02C01", "9");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E04P03M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E05P03M02C01).
     * 
     */
    @Test
    public void testT10L10_E05P03M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E05P03M02C01", "10");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E05P03M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E01P01M01C02).
     * 
     */
    @Test
    public void testT10L10_E01P01M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E01P01M01C02", "11");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E01P01M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E02P01M01C02).
     * 
     */
    @Test
    public void testT10L10_E02P01M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E02P01M01C02", "12");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E02P01M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E03P01M01C02).
     * 
     */
    @Test
    public void testT10L10_E03P01M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E03P01M01C02", "13");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E03P01M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E04P01M01C02).
     * 
     */
    @Test
    public void testT10L10_E04P01M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E04P01M01C02", "14");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E04P01M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E05P01M01C02).
     * 
     */
    @Test
    public void testT10L10_E05P01M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E05P01M01C02", "15");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E05P01M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E01P02M01C02).
     * 
     */
    @Test
    public void testT10L10_E01P02M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E01P02M01C02", "16");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E01P02M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E02P02M01C02).
     * 
     */
    @Test
    public void testT10L10_E02P02M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E02P02M01C02", "17");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E02P02M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E03P02M01C02).
     * 
     */
    @Test
    public void testT10L10_E03P02M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E03P02M01C02", "18");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E03P02M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E04P02M01C02).
     * 
     */
    @Test
    public void testT10L10_E04P02M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E04P02M01C02", "19");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E04P02M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E05P02M01C02).
     * 
     */
    @Test
    public void testT10L10_E05P02M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E05P02M01C02", "20");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E05P02M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E01P03M01C02).
     * 
     */
    @Test
    public void testT10L10_E01P03M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E01P03M01C02", "21");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E01P03M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E02P03M01C02).
     * 
     */
    @Test
    public void testT10L10_E02P03M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E02P03M01C02", "22");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E02P03M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E03P03M01C02).
     * 
     */
    @Test
    public void testT10L10_E03P03M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E03P03M01C02", "23");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E03P03M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E04P03M01C02).
     * 
     */
    @Test
    public void testT10L10_E04P03M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E04P03M01C02", "24");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E04P03M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E05P03M01C02).
     * 
     */
    @Test
    public void testT10L10_E05P03M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E05P03M01C02", "25");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E05P03M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E01P01M02C02).
     * 
     */
    @Test
    public void testT10L10_E01P01M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E01P01M02C02", "26");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E01P01M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E02P01M02C02).
     * 
     */
    @Test
    public void testT10L10_E02P01M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E02P01M02C02", "27");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E02P01M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E03P01M02C02).
     * 
     */
    @Test
    public void testT10L10_E03P01M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E03P01M02C02", "28");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E03P01M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E04P01M02C02).
     * 
     */
    @Test
    public void testT10L10_E04P01M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E04P01M02C02", "29");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E04P01M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E05P01M02C02).
     * 
     */
    @Test
    public void testT10L10_E05P01M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E05P01M02C02", "30");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E05P01M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E01P02M02C02).
     * 
     */
    @Test
    public void testT10L10_E01P02M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E01P02M02C02", "31");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E01P02M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E02P02M02C02).
     * 
     */
    @Test
    public void testT10L10_E02P02M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E02P02M02C02", "32");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E02P02M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E03P02M02C02).
     * 
     */
    @Test
    public void testT10L10_E03P02M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E03P02M02C02", "33");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E03P02M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E04P02M02C02).
     * 
     */
    @Test
    public void testT10L10_E04P02M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E04P02M02C02", "34");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E04P02M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E05P02M02C02).
     * 
     */
    @Test
    public void testT10L10_E05P02M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E05P02M02C02", "35");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E05P02M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E01P03M02C02).
     * 
     */
    @Test
    public void testT10L10_E01P03M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E01P03M02C02", "36");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E01P03M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E02P03M02C02).
     * 
     */
    @Test
    public void testT10L10_E02P03M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E02P03M02C02", "37");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E02P03M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E03P03M02C02).
     * 
     */
    @Test
    public void testT10L10_E03P03M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E03P03M02C02", "38");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E03P03M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E04P03M02C02).
     * 
     */
    @Test
    public void testT10L10_E04P03M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E04P03M02C02", "39");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E04P03M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L10) and row (E05P03M02C02).
     * 
     */
    @Test
    public void testT10L10_E05P03M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L10", "E05P03M02C02", "40");

        NonRootModelElement src = selectTL("T10L10");

        NonRootModelElement dest = selectEPMC("E05P03M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P01M01C01).
     * 
     */
    @Test
    public void testT10L11_E01P01M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P01M01C01", "41");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P01M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P01M01C01).
     * 
     */
    @Test
    public void testT10L11_E02P01M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P01M01C01", "42");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P01M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P01M01C01).
     * 
     */
    @Test
    public void testT10L11_E03P01M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P01M01C01", "43");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P01M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P01M01C01).
     * 
     */
    @Test
    public void testT10L11_E04P01M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P01M01C01", "44");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P01M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P01M01C01).
     * 
     */
    @Test
    public void testT10L11_E05P01M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P01M01C01", "45");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P01M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P02M01C01).
     * 
     */
    @Test
    public void testT10L11_E01P02M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P02M01C01", "46");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P02M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P02M01C01).
     * 
     */
    @Test
    public void testT10L11_E02P02M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P02M01C01", "47");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P02M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P02M01C01).
     * 
     */
    @Test
    public void testT10L11_E03P02M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P02M01C01", "48");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P02M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P02M01C01).
     * 
     */
    @Test
    public void testT10L11_E04P02M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P02M01C01", "49");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P02M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P02M01C01).
     * 
     */
    @Test
    public void testT10L11_E05P02M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P02M01C01", "50");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P02M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P03M01C01).
     * 
     */
    @Test
    public void testT10L11_E01P03M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P03M01C01", "51");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P03M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P03M01C01).
     * 
     */
    @Test
    public void testT10L11_E02P03M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P03M01C01", "52");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P03M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P03M01C01).
     * 
     */
    @Test
    public void testT10L11_E03P03M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P03M01C01", "53");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P03M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P03M01C01).
     * 
     */
    @Test
    public void testT10L11_E04P03M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P03M01C01", "54");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P03M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P03M01C01).
     * 
     */
    @Test
    public void testT10L11_E05P03M01C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P03M01C01", "55");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P03M01C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P01M02C01).
     * 
     */
    @Test
    public void testT10L11_E01P01M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P01M02C01", "56");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P01M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P01M02C01).
     * 
     */
    @Test
    public void testT10L11_E02P01M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P01M02C01", "57");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P01M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P01M02C01).
     * 
     */
    @Test
    public void testT10L11_E03P01M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P01M02C01", "58");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P01M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P01M02C01).
     * 
     */
    @Test
    public void testT10L11_E04P01M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P01M02C01", "59");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P01M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P01M02C01).
     * 
     */
    @Test
    public void testT10L11_E05P01M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P01M02C01", "60");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P01M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P02M02C01).
     * 
     */
    @Test
    public void testT10L11_E01P02M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P02M02C01", "61");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P02M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P02M02C01).
     * 
     */
    @Test
    public void testT10L11_E02P02M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P02M02C01", "62");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P02M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P02M02C01).
     * 
     */
    @Test
    public void testT10L11_E03P02M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P02M02C01", "63");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P02M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P02M02C01).
     * 
     */
    @Test
    public void testT10L11_E04P02M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P02M02C01", "64");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P02M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P02M02C01).
     * 
     */
    @Test
    public void testT10L11_E05P02M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P02M02C01", "65");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P02M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P03M02C01).
     * 
     */
    @Test
    public void testT10L11_E01P03M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P03M02C01", "66");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P03M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P03M02C01).
     * 
     */
    @Test
    public void testT10L11_E02P03M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P03M02C01", "67");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P03M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P03M02C01).
     * 
     */
    @Test
    public void testT10L11_E03P03M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P03M02C01", "68");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P03M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P03M02C01).
     * 
     */
    @Test
    public void testT10L11_E04P03M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P03M02C01", "69");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P03M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P03M02C01).
     * 
     */
    @Test
    public void testT10L11_E05P03M02C01() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P03M02C01", "70");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P03M02C01");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P01M01C02).
     * 
     */
    @Test
    public void testT10L11_E01P01M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P01M01C02", "71");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P01M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P01M01C02).
     * 
     */
    @Test
    public void testT10L11_E02P01M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P01M01C02", "72");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P01M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P01M01C02).
     * 
     */
    @Test
    public void testT10L11_E03P01M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P01M01C02", "73");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P01M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P01M01C02).
     * 
     */
    @Test
    public void testT10L11_E04P01M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P01M01C02", "74");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P01M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P01M01C02).
     * 
     */
    @Test
    public void testT10L11_E05P01M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P01M01C02", "75");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P01M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P02M01C02).
     * 
     */
    @Test
    public void testT10L11_E01P02M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P02M01C02", "76");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P02M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P02M01C02).
     * 
     */
    @Test
    public void testT10L11_E02P02M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P02M01C02", "77");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P02M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P02M01C02).
     * 
     */
    @Test
    public void testT10L11_E03P02M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P02M01C02", "78");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P02M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P02M01C02).
     * 
     */
    @Test
    public void testT10L11_E04P02M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P02M01C02", "79");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P02M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P02M01C02).
     * 
     */
    @Test
    public void testT10L11_E05P02M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P02M01C02", "80");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P02M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P03M01C02).
     * 
     */
    @Test
    public void testT10L11_E01P03M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P03M01C02", "81");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P03M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P03M01C02).
     * 
     */
    @Test
    public void testT10L11_E02P03M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P03M01C02", "82");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P03M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P03M01C02).
     * 
     */
    @Test
    public void testT10L11_E03P03M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P03M01C02", "83");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P03M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P03M01C02).
     * 
     */
    @Test
    public void testT10L11_E04P03M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P03M01C02", "84");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P03M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P03M01C02).
     * 
     */
    @Test
    public void testT10L11_E05P03M01C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P03M01C02", "85");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P03M01C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P01M02C02).
     * 
     */
    @Test
    public void testT10L11_E01P01M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P01M02C02", "86");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P01M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P01M02C02).
     * 
     */
    @Test
    public void testT10L11_E02P01M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P01M02C02", "87");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P01M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P01M02C02).
     * 
     */
    @Test
    public void testT10L11_E03P01M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P01M02C02", "88");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P01M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P01M02C02).
     * 
     */
    @Test
    public void testT10L11_E04P01M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P01M02C02", "89");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P01M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P01M02C02).
     * 
     */
    @Test
    public void testT10L11_E05P01M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P01M02C02", "90");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P01M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P02M02C02).
     * 
     */
    @Test
    public void testT10L11_E01P02M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P02M02C02", "91");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P02M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P02M02C02).
     * 
     */
    @Test
    public void testT10L11_E02P02M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P02M02C02", "92");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P02M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P02M02C02).
     * 
     */
    @Test
    public void testT10L11_E03P02M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P02M02C02", "93");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P02M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P02M02C02).
     * 
     */
    @Test
    public void testT10L11_E04P02M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P02M02C02", "94");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P02M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P02M02C02).
     * 
     */
    @Test
    public void testT10L11_E05P02M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P02M02C02", "95");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P02M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("Declaration was shown in model explorer, and canvas.", checkResult_elementShownInMEandCanvas(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E01P03M02C02).
     * 
     */
    @Test
    public void testT10L11_E01P03M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E01P03M02C02", "96");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E01P03M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E02P03M02C02).
     * 
     */
    @Test
    public void testT10L11_E02P03M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E02P03M02C02", "97");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E02P03M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E03P03M02C02).
     * 
     */
    @Test
    public void testT10L11_E03P03M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E03P03M02C02", "98");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E03P03M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E04P03M02C02).
     * 
     */
    @Test
    public void testT10L11_E04P03M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E04P03M02C02", "99");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E04P03M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

    /**
     * Perform the test for the given matrix column (T10L11) and row (E05P03M02C02).
     * 
     */
    @Test
    public void testT10L11_E05P03M02C02() throws Exception {
        setUp();
        test_id = getTestId("T10L11", "E05P03M02C02", "100");

        NonRootModelElement src = selectTL("T10L11");

        NonRootModelElement dest = selectEPMC("E05P03M02C02");

        TL_EPMC_Action(src, dest);
        assertTrue("The selection made based on cursor position is not valid", checkResult_invalidSelection(src,dest));
        
        GraphicalEditor editor = getActiveEditor();
        if(editor != null && useDrawResults) {
           validateOrGenerateResults(editor, generateResults);
        }
        tearDown();
    }

}
