//=====================================================================
//
// NOTE: This file was generated, but is maintained by hand.
// Generated by: UnitTestGenerator.pl
// Version:      1.15
// Matrix:       9761_9762_find_declarations_matrix.txt
//
//=====================================================================

package org.xtuml.bp.ui.text.editor.oal.opendeclaration;

import org.eclipse.ui.IEditorPart;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import org.xtuml.bp.core.*;
import org.xtuml.bp.core.common.NonRootModelElement;
import org.xtuml.bp.test.common.*;
import org.xtuml.bp.ui.canvas.*;
import org.xtuml.bp.ui.graphics.editor.*;
import org.xtuml.bp.ui.canvas.test.*;

public class OpenDeclarationTests extends CanvasTest {
    public static boolean generateResults = false;
    public static boolean useDrawResults = true;

    String test_id = "";

    protected String getResultName() {
        return getClass().getSimpleName() + "_" + test_id;
    }

    protected GraphicalEditor fActiveEditor;

    protected GraphicalEditor getActiveEditor() {
        return fActiveEditor;
    }

    public OpenDeclarationTests(String subTypeClassName, String subTypeArg0) {
        super(subTypeClassName, subTypeArg0);
    }

    protected String getTestId(String src, String dest, String count) {
        return "test_" + count;
    }

    @Before
    public void setUp() throws Exception {
        super.setUp();
    }

    @After
    public void tearDown() throws Exception {
        super.tearDown();
    }

    /**
     * "EPMC" is one of the degrees of freedom as specified in this issues
     * test matrix.
     * This routine gets the "EPMC" instance from the given name.
     * 
     * @param element The degree of freedom instance to retrieve
     * @return A model element used in the test as specified by the test matrix
     */
    NonRootModelElement selectEPMC(String element) {
        return selectEPMC(element, null);
    }

    /**
     * "EPMC" is one of the degrees of freedom as specified in this issues
     * test matrix.
     * This routine gets the "EPMC" instance from the given name.
     * 
     * @param element The degree of freedom instance to retrieve
     * @param extraData Extra data needed for selection
     * @return A model element used in the test as specified by the test matrix
     */
    NonRootModelElement selectEPMC(String element, Object extraData) {
        NonRootModelElement nrme = null;
        if (element.equalsIgnoreCase("E01P01M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P01M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P01M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P01M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P02M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P02M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P02M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P02M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P03M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P03M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P03M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E01P03M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P01M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P01M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P01M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P01M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P02M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P02M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P02M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P02M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P03M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P03M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P03M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E02P03M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P01M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P01M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P01M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P01M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P02M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P02M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P02M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P02M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P03M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P03M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P03M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E03P03M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P01M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P01M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P01M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P01M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P02M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P02M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P02M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P02M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P03M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P03M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P03M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E04P03M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P01M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P01M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P01M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P01M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P02M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P02M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P02M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P02M02C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P03M01C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P03M01C02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P03M02C01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("E05P03M02C02")) {
            //TODO: Implement
        } else        assertTrue("An instance with degree of freedom type \"EPMC\" was not found.  Instance Name: " + element + ".", nrme!=null);
        return nrme;
    }

    /**
     * "LT" is one of the degrees of freedom as specified in this issues
     * test matrix.
     * This routine gets the "LT" instance from the given name.
     * 
     * @param element The degree of freedom instance to retrieve
     * @return A model element used in the test as specified by the test matrix
     */
    NonRootModelElement selectLT(String element) {
        return selectLT(element, null);
    }

    /**
     * "LT" is one of the degrees of freedom as specified in this issues
     * test matrix.
     * This routine gets the "LT" instance from the given name.
     * 
     * @param element The degree of freedom instance to retrieve
     * @param extraData Extra data needed for selection
     * @return A model element used in the test as specified by the test matrix
     */
    NonRootModelElement selectLT(String element, Object extraData) {
        NonRootModelElement nrme = null;
        if (element.equalsIgnoreCase("L01T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L01T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L01T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L01T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L01T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L01T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L01T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L01T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L01T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L01T10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L02T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L02T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L02T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L02T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L02T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L02T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L02T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L02T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L02T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L02T10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L03T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L03T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L03T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L03T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L03T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L03T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L03T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L03T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L03T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L03T10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L04T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L04T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L04T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L04T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L04T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L04T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L04T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L04T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L04T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L04T10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L05T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L05T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L05T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L05T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L05T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L05T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L05T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L05T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L05T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L05T10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L06T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L06T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L06T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L06T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L06T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L06T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L06T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L06T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L06T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L06T10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L07T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L07T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L07T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L07T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L07T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L07T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L07T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L07T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L07T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L07T10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L08T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L08T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L08T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L08T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L08T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L08T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L08T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L08T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L08T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L08T10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L09T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L09T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L09T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L09T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L09T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L09T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L09T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L09T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L09T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L09T10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L10T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L10T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L10T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L10T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L10T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L10T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L10T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L10T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L10T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L10T10")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L11T01")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L11T02")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L11T03")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L11T04")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L11T05")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L11T06")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L11T07")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L11T08")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L11T09")) {
            //TODO: Implement
        } else if (element.equalsIgnoreCase("L11T10")) {
            //TODO: Implement
        } 
        assertTrue("An instance with degree of freedom type \"LT\" was not found.  Instance Name: " + element + ".", nrme!=null);
        return nrme;
    }

    /**
     * This routine performs the action associated with a matrix cell.
     * The parameters represent model instances aquired based on the specifed
     * column instance and row instance.
     * 
     * @param columnInstance Model instance from the column
     * @param rowInstance Model instance from the row
     */
    void LT_EPMC_Action(NonRootModelElement columnInstance, NonRootModelElement rowInstance) {
        //TODO: Implement
    }

    /**
    * This function verifies an expected result.
    *
    * @param source A model element instance aquired through a action taken
    *               on a column of the matrix.
    * @param destination A model element instance aquired through a action taken
    *                    taken on a row of the matrix.
    * @return true if the test succeeds, false if it fails
    */
    boolean checkResult_elementShownInCanvasNotME(NonRootModelElement source, NonRootModelElement destination) {
        boolean elementShownInCanvasNotME = false;
        //TODO: Implement
        return elementShownInCanvasNotME;
    }


    /**
    * This function verifies an expected result.
    *
    * @param source A model element instance aquired through a action taken
    *               on a column of the matrix.
    * @param destination A model element instance aquired through a action taken
    *                    taken on a row of the matrix.
    * @return true if the test succeeds, false if it fails
    */
    boolean checkResult_invalidSelection(NonRootModelElement source, NonRootModelElement destination) {
        boolean invalidSelection = false;
        //TODO: Implement
        return invalidSelection;
    }


    /**
    * This function verifies an expected result.
    *
    * @param source A model element instance aquired through a action taken
    *               on a column of the matrix.
    * @param destination A model element instance aquired through a action taken
    *                    taken on a row of the matrix.
    * @return true if the test succeeds, false if it fails
    */
    boolean checkResult_transientDeclarationShown(NonRootModelElement source, NonRootModelElement destination) {
        boolean transientDeclarationShown = false;
        //TODO: Implement
        return transientDeclarationShown;
    }


    /**
    * This function verifies an expected result.
    *
    * @param source A model element instance aquired through a action taken
    *               on a column of the matrix.
    * @param destination A model element instance aquired through a action taken
    *                    taken on a row of the matrix.
    * @return true if the test succeeds, false if it fails
    */
    boolean checkResult_elementShownInMEandCanvas(NonRootModelElement source, NonRootModelElement destination) {
        boolean elementShownInMEandCanvas = false;
        //TODO: Implement
        return elementShownInMEandCanvas;
    }


    /**
    * This function verifies an expected result.
    *
    * @param source A model element instance aquired through a action taken
    *               on a column of the matrix.
    * @param destination A model element instance aquired through a action taken
    *                    taken on a row of the matrix.
    * @return true if the test succeeds, false if it fails
    */
    boolean checkResult_elementShownInMENotCanvas(NonRootModelElement source, NonRootModelElement destination) {
        boolean elementShownInMENotCanvas = false;
        //TODO: Implement
        return elementShownInMENotCanvas;
    }


}
